services:
  skin_lesion_api_service:
    container_name: skin_lesion_api_container
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/app
      - ../weights:/app/weights:rw
      - ../preprocess_data:/app/api/preprocess_data
      - /root:/root:rw      
    environment:
      - API_HOSTNAME=${API_HOSTNAME}
      - API_PORT=${API_PORT}
      - MODEL_FOLDER_PATH=${MODEL_FOLDER_PATH}
      - NUM_LABELS=${NUM_LABELS}
      - NUM_HEADS=${NUM_HEADS}
      - VOCAB_SIZE=${VOCAB_SIZE}
      - CNN_MODEL_NAME=${CNN_MODEL_NAME}
      - TEXT_PROCESSOR_NAME=${TEXT_PROCESSOR_NAME}
      - ATTENTION_MECHANISM=${ATTENTION_MECHANISM}
    ports:
      - ${API_PORT}:8008
    command: "python3 /app/api/api.py"
    tty: true
    restart: always
    cpus: 3
    mem_limit: 2000MB
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia  
    networks:
      - default
